### ISSUE TITLE
Issue with Age causes observed cache TTL to be twice the Max-Age

### ISSUE THREAD

**Issue by bmancone** [guzzle/cache-subscriber#59]
Hi,

I'am using the cache-subscriber to cache requests from a varnish proxy.

I noticed that when the proxy returns `Cache-Control: public, max-age=60` and  `Age: 17`, the response is cached for 60 seconds.

Indeed, the `Age` header is copied from the original response but is never incremented, which leads to calls to `CacheSubscriber::validate` and `Utils::isResponseValid` that always returns the same difference between `max-age` and `age`.

**Comment by bmancone** [comment]
@mtdowling, what do you think about this issue? :-)

**Comment by yched** [comment]
+1

The fix seems perfectly reasonable - the age of a response fetched from cache cannot be simply equal to the age it had back when it was first received and written into the cache ?
Instead, the age used to check whether it is still valid should be "age when the response was cached + time elapsed since then" ?

**Comment by yched** [comment]
Worse - it seems that the current logic around "stale / freshness" is broken too : Utils::getFreshness() is based on values (max-age and age) that are never updated, so the "freshness" of a response never gets to change ?

By fixing Utils::getResponseAge(), it looks like the PR fixes that as well ?

**Comment by bmancone** [comment]
It turned out that `getResponseAge` is not the right place to increment the age, since it is called multiple times on a response fetched from cache, and the age was then incremented multiple times.

Instead, incrementing needs to happen only in `isResponseValid`:.
- After calling `getResponseAge`, increment the age before comparing `max-age` and `age`. 
- Save the incremented age back in the response so that `getFreshness` also reasons on the right age.

**Comment by yched** [comment]
Oops. Indeed.
The previous code in the PR did fix Guzzle Cache entries being served past their valid age. But the fix was also causing the cached entries to expire sooner than they should, which I didn't notice...

The latest code works great.

@mtdowling : what do you think of the fix ? The fact that Guzzle Cache can currently double a response TTL when the served response age was nearing its max-age is a bit of a dealbreaker in some cases :-)

**Comment by bmancone** [comment]
Fixed in #60
